import type { Catalogo } from "./motor";

/**
 * Manual de Certificação da FPF · Futebol masculino · época 2026/27.
 *
 * Transcrito do manual da Direção de Certificação e Licenciamento (setembro de
 * 2026), questão a questão. Cada linha é um requisito: o código segue a
 * numeração do manual, `points` ou `tiers` dizem quanto vale, `mandatory` diz
 * a partir de que patamar é de cumprimento obrigatório, e `condition` diz a
 * que clubes se aplica.
 *
 * ## Porque é que isto é código e não uma tabela
 *
 * O manual muda todos os anos — a própria FPF assinala as páginas que mudaram.
 * Aqui a diferença entre duas épocas é um diff que se lê, e um manual novo é um
 * ficheiro novo ao lado deste. Futsal e futebol feminino têm manuais próprios
 * e entram da mesma maneira, sem migração.
 *
 * ## Os patamares
 *
 * `C` desde o CBFF, `E` desde as escolas de 1 e 2 estrelas, `T` desde as 3
 * estrelas, `Q` só para as 4 e 5. São cumulativos: quem quer as 3 estrelas
 * cumpre os `C`, os `E` e os `T`.
 *
 * ## O que ficou por confirmar com a associação
 *
 * - O subcritério 3.3 vale 0,75 no índice do manual, mas as três questões
 *   somam 1,0 (0,25 + 0,5 + 0,25). Ficaram as três a 0,25 para o total dar 100.
 * - Nas obrigatórias das escolas aparece "apenas 1 treino semanal em recinto
 *   que não seja fechado", que não existe na grelha do futebol. Parece vir do
 *   manual de futsal e ficou de fora.
 * - As condições `rec` em 3.2.1.2 a 3.2.1.4 não estão escritas no manual:
 *   saem da aritmética das questões que mudam de valor "para as Entidades que
 *   não façam recrutamento" (os 5,5 pontos que se redistribuem são exactamente
 *   os destas questões, mais as do 3.2.2 e do 3.3).
 *
 * Total verificado por `npm run test:certificacao`: 100 pontos, 12 do avaliador.
 */
export const FPF_F11M_2026: Catalogo = {
  key: "fpf-f11m-2026",
  title: "FPF · Futebol masculino",
  manual: "Manual de Certificação, setembro de 2026",
  criteria: [
    { criterion: 0, name: "Dados gerais e declarações", max: 0 },
    { criterion: 1, name: "Planeamento estratégico e orçamento", max: 7 },
    { criterion: 2, name: "Estrutura organizacional e Manual de Acolhimento", max: 7 },
    { criterion: 3, name: "Recrutamento e angariação", max: 12 },
    { criterion: 4, name: "Formação desportiva", max: 18 },
    { criterion: 5, name: "Acompanhamento médico-desportivo", max: 13 },
    { criterion: 6, name: "Acompanhamento escolar, pessoal e social", max: 9 },
    { criterion: 7, name: "Recursos humanos", max: 16 },
    { criterion: 8, name: "Instalações e logística", max: 10 },
    { criterion: 9, name: "Produtividade", max: 8 },
  ],
  groups: {
    "0.4": "Declarações de compromisso",
    "1.1": "Missão, visão, valores e objetivos",
    "1.2": "Ética e integridade",
    "1.3": "Orçamento",
    "2.1": "Posição no organograma do clube",
    "2.2.1": "Manual de Acolhimento e Boas Práticas",
    "2.2.2": "Normas de conduta",
    "2.2.3": "Normas de acompanhamento de praticantes",
    "2.2.4": "Infrações e quadro disciplinar",
    "3.1": "Recursos humanos de recrutamento e angariação",
    "3.2.1": "Política de recrutamento e angariação",
    "3.2.2": "Procedimentos de recrutamento",
    "3.2.3": "Procedimentos de angariação",
    "3.3": "Praticantes não-nacionais",
    "3.4": "Estrutura piramidal",
    "3.5": "Avaliação qualitativa",
    "4.1": "Documento Orientador Técnico",
    "4.2": "Dossier de treino",
    "4.3.1": "Plano de transição",
    "4.3.2": "Reuniões de articulação",
    "4.4": "Avaliação qualitativa",
    "5.1": "Plano de atividades do departamento médico",
    "5.2": "Recursos humanos do departamento médico",
    "5.3": "Instalações e equipamentos médicos",
    "5.4.1": "Apoio a treinos e jogos",
    "5.4.2": "Clínica, tratamento e reabilitação",
    "5.4.3": "Apoio ao praticante e controlo médico do treino",
    "5.4.4": "Formação na área médica",
    "5.5": "Avaliação qualitativa",
    "6.1": "Articulação com as escolas",
    "6.2": "Acompanhamento escolar e social",
    "6.3": "Praticantes deslocados (D.R.E.)",
    "6.4": "Proteção de menores",
    "6.5": "Formação complementar",
    "6.6": "Carreira dual",
    "6.7": "Avaliação qualitativa",
    "7.1": "Diretor da entidade formadora",
    "7.2.1": "Diretor ou coordenador técnico",
    "7.2.2": "Treinadores",
    "7.3": "Outros recursos da área técnica",
    "7.4": "Staff administrativo e logístico",
    "7.5": "Avaliação qualitativa",
    "8.1": "Campos de treino",
    "8.2": "Vestiários e balneários",
    "8.3": "Gabinetes e salas de trabalho",
    "8.4": "Salas de reunião, estudo e formação",
    "8.5": "Serviços administrativos",
    "8.6": "Ginásio",
    "8.7": "Alojamento de praticantes D.R.E.",
    "8.8": "Transportes",
    "8.9": "Avaliação qualitativa",
    "9.1": "Chegada à equipa principal",
    "9.2": "Direitos económicos",
    "9.3": "Seleções",
    "9.4": "Competições profissionais",
    "9.5": "Competições nacionais",
    "9.6": "Retenção no fim da formação",
  },
  requirements: [
  // 0 · Dados gerais e declarações (sem pontos)
  { code: "D01", criterion: 0, group: "0.4", text: "Conhece e respeita as Linhas Orientadoras da Integridade da FPF", points: 0, mandatory: "C", mode: "declaration", source: "declaration" },
  { code: "D02", criterion: 0, group: "0.4", text: "Conhece e respeita as Linhas Orientadoras de Recrutamento e Angariação e as normas regulamentares", points: 0, mandatory: "C", mode: "declaration", source: "declaration" },
  { code: "D03", criterion: 0, group: "0.4", text: "Cumpre a proteção de menores e o Diretor, o Gestor de Carreira Dual ou o Responsável D.R.E. fez o curso online da UEFA de salvaguarda", points: 0, mandatory: "C", mode: "declaration", source: "staff", evidence: "Certificado do curso UEFA (15 minutos)" },
  { code: "D04", criterion: 0, group: "0.4", text: "Conhece e cumpre os procedimentos para praticantes não-nacionais não residentes", points: 0, mandatory: "C", mode: "declaration", source: "declaration" },
  { code: "D05", criterion: 0, group: "0.4", text: "Todos os praticantes têm seguro desportivo e exame médico-desportivo válidos e estão inscritos no Score ou registados na FPF", points: 0, mandatory: "C", mode: "data", source: "teams" },
  { code: "D06", criterion: 0, group: "0.4", text: "Conhece e respeita as Etapas de Desenvolvimento do Praticante", points: 0, mandatory: "C", mode: "declaration", source: "declaration" },
  { code: "D07", criterion: 0, group: "0.4", text: "Todos os praticantes concluíram a escolaridade obrigatória ou frequentam um estabelecimento de ensino", points: 0, mandatory: "C", mode: "data", source: "school" },
  { code: "D08", criterion: 0, group: "0.4", text: "Os praticantes convocados para seleções nacionais e distritais comparecem", points: 0, mandatory: "C", mode: "declaration", source: "declaration" },
  { code: "D09", criterion: 0, group: "0.4", text: "Pediu e validou os registos criminais de todos os restantes recursos humanos e prestadores de serviços", points: 0, mandatory: "C", mode: "data", source: "staff" },
  { code: "D10", criterion: 0, group: "0.4", text: "Só usa equipamentos e materiais que cumprem as condições legais e de segurança", points: 0, mandatory: "C", mode: "declaration", source: "declaration" },
  { code: "D11", criterion: 0, group: "0.4", text: "Os transportes próprios das equipas de formação cumprem as condições regulamentares", points: 0, mandatory: "C", mode: "declaration", source: "declaration" },
  { code: "D12", criterion: 0, group: "0.4", text: "Não tem dívidas vencidas aos recursos humanos e vai cumprir os compromissos da época", points: 0, mandatory: "C", mode: "declaration", source: "declaration" },

  // 1 · Planeamento estratégico e orçamento (7 pontos)
  { code: "1.1.1", criterion: 1, group: "1.1", text: "Missão, visão, valores e objetivos da época definidos, conhecidos pelos colaboradores, com a missão afixada e publicada", points: 3, mandatory: "E", mode: "document", source: "documents", evidence: "Documento com missão, visão, valores e objetivos + fotografia da missão afixada" },
  { code: "1.2.1", criterion: 1, group: "1.2", text: "Registo na Bandeira da Ética (IPDJ) com candidatura nesta época", tiers: [{ label: "Iniciativa submetida", points: 0.25, mandatory: "E" }, { label: "Projeto, departamento ou clube submetido", points: 0.5 }, { label: "Iniciativa certificada", points: 0.75 }, { label: "Projeto, departamento ou clube certificado", points: 1 }], mode: "document", source: "documents", evidence: "Comprovativo da candidatura, descritivo e comprovativo de realização" },
  { code: "1.2.2", criterion: 1, group: "1.2", text: "Responsável pela Ética e Integridade identificado, com registo criminal e CV", points: 0.75, mandatory: "T", mode: "data", source: "staff", evidence: "Descrição das tarefas regulares do responsável" },
  { code: "1.3.1", criterion: 1, group: "1.3", text: "Peso do orçamento da formação no orçamento global da modalidade", tiers: [{ label: "Escalão mínimo da banda", points: 0.5 }, { label: "Escalão intermédio", points: 1 }, { label: "Escalão superior", points: 1.5 }], mode: "data", source: "finance", note: "As bandas dependem do orçamento global: até 100 mil € pede 25%, 25 a 50% ou mais de 50%; sem equipa sénior pede 40%, 40 a 80% ou mais de 80%." },
  { code: "1.3.2", criterion: 1, group: "1.3", text: "Orçamento da formação com as rubricas de proveitos e custos por área operacional", points: 0.75, mandatory: "E", mode: "data", source: "finance", evidence: "Orçamento por área: direção, técnica, recrutamento, médica, escolar e social, instalações, transportes, logística" },

  // 2 · Estrutura organizacional e Manual de Acolhimento (7 pontos)
  { code: "2.1.1", criterion: 2, group: "2.1", text: "A entidade formadora está no organograma do clube e o diretor reporta à direção", points: 0.5, mode: "document", source: "documents", evidence: "Organograma do clube" },
  { code: "2.2.1.1", criterion: 2, group: "2.2.1", text: "Existe Manual de Acolhimento e Boas Práticas e todos os praticantes e encarregados o conhecem", points: 0.5, mandatory: "C", mode: "data", source: "club-app", evidence: "Manual completo com índice + comprovativo de que os encarregados tomaram conhecimento" },
  { code: "2.2.1.2", criterion: 2, group: "2.2.1", text: "O manual descreve missão, visão, objetivos e informação estratégica para a comunidade", points: 0.5, mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.1.3", criterion: 2, group: "2.2.1", text: "O manual diz as condições de inscrição, o valor das mensalidades e a aquisição de equipamentos", points: 0.5, mandatory: "C", mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.2.1", criterion: 2, group: "2.2.2", text: "Normas de conduta entre praticantes, dirigentes, técnicos e staff", points: 0.25, mandatory: "T", mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.2.2", criterion: 2, group: "2.2.2", text: "Normas de conduta em treino e competição", points: 0.25, mandatory: "T", mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.2.3", criterion: 2, group: "2.2.2", text: "Indicações sobre integridade, apostas e match fixing", points: 0.5, mandatory: "T", mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.2.4", criterion: 2, group: "2.2.2", text: "Normas de conduta na escola", points: 0.5, mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.2.5", criterion: 2, group: "2.2.2", text: "Normas de conduta nos transportes", points: 0.5, mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.3.1", criterion: 2, group: "2.2.3", text: "Recomendações alimentares, de nutrição e hidratação alinhadas com o plano nutricional", points: 0.5, mandatory: "T", mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.3.2", criterion: 2, group: "2.2.3", text: "Normas de acompanhamento médico-desportivo com os infogramas de emergência", points: 0.5, mandatory: "T", mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.3.3", criterion: 2, group: "2.2.3", text: "Normas de acompanhamento escolar, pessoal e social", points: 0.5, mandatory: "T", mode: "document", source: "documents", evidence: "Capítulo do manual", note: "Vale 1 ponto nos clubes sem praticantes D.R.E." },
  { code: "2.2.3.4", criterion: 2, group: "2.2.3", text: "Normas sobre as relações com pais e encarregados de educação", points: 0.5, mandatory: "E", mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.3.5", criterion: 2, group: "2.2.3", text: "Normas especiais de acompanhamento de praticantes deslocados (D.R.E.)", points: 0.5, mandatory: "C", condition: "dre", mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.4.1", criterion: 2, group: "2.2.4", text: "Infrações e quadro disciplinar dos praticantes, incluindo bullying, assédio e violência", points: 0.25, mandatory: "T", mode: "document", source: "documents", evidence: "Capítulo do manual" },
  { code: "2.2.4.2", criterion: 2, group: "2.2.4", text: "Infrações e quadro disciplinar dos pais e encarregados", points: 0.25, mandatory: "E", mode: "document", source: "documents", evidence: "Capítulo do manual" },

  // 3 · Recrutamento e angariação (12 pontos)
  { code: "3.1.1.1", criterion: 3, group: "3.1", text: "Pessoas com funções de recrutamento ou angariação identificadas, com registo criminal e CV", points: 0.5, mode: "data", source: "staff" },
  { code: "3.1.1.2", criterion: 3, group: "3.1", text: "Descrição de como a área de recrutamento e angariação está constituída e organizada", points: 0.5, mode: "document", source: "documents", evidence: "Composição, organização e funções da área" },
  { code: "3.1.2.1", criterion: 3, group: "3.1", text: "Formação interna anual aos recrutadores e observadores sobre a política, os procedimentos e as linhas de ética da FPF", points: 0.75, mandatory: "Q", mode: "data", source: "training-actions", evidence: "Planeamento das ações + registo de realização" },
  { code: "3.1.2.2", criterion: 3, group: "3.1", text: "Essas formações têm documentos de suporte", points: 0.25, mode: "document", source: "training-actions", evidence: "Exemplo do documento usado na formação" },
  { code: "3.2.1.1", criterion: 3, group: "3.2.1", text: "Política de recrutamento e de angariação definida e documentada", points: 0.5, mandatory: "E", mode: "document", source: "documents", evidence: "Documento completo com índice", note: "Vale 2 pontos nos clubes que não fazem recrutamento." },
  { code: "3.2.1.2", criterion: 3, group: "3.2.1", text: "A política inclui o conjunto global de competências do praticante", points: 0.5, condition: "rec", mode: "document", source: "documents", evidence: "Capítulo da política" },
  { code: "3.2.1.3", criterion: 3, group: "3.2.1", text: "A política inclui as competências do praticante por escalão", points: 0.5, condition: "rec", mode: "document", source: "documents", evidence: "Capítulo da política" },
  { code: "3.2.1.4", criterion: 3, group: "3.2.1", text: "A política define a abrangência geográfica", points: 0.5, condition: "rec", mode: "document", source: "documents", evidence: "Capítulo da política" },
  { code: "3.2.2.1", criterion: 3, group: "3.2.2", text: "Procedimentos de recrutamento definidos e documentados", points: 0.5, mandatory: "E", condition: "rec", mode: "document", source: "documents", evidence: "Documento completo com índice" },
  { code: "3.2.2.2", criterion: 3, group: "3.2.2", text: "Os procedimentos definem como se observa", points: 0.5, condition: "rec", mode: "document", source: "documents", evidence: "Capítulo dos procedimentos" },
  { code: "3.2.2.3", criterion: 3, group: "3.2.2", text: "Os procedimentos definem os parâmetros de seleção", points: 0.5, condition: "rec", mode: "document", source: "documents", evidence: "Capítulo dos procedimentos" },
  { code: "3.2.2.4", criterion: 3, group: "3.2.2", text: "Os procedimentos definem como se regista a informação", points: 0.5, condition: "rec", mode: "document", source: "documents", evidence: "Capítulo dos procedimentos" },
  { code: "3.2.2.5", criterion: 3, group: "3.2.2", text: "Base de dados de recrutamento", tiers: [{ label: "Folha Excel ou similar", points: 0.25 }, { label: "Aplicação de recrutamento", points: 0.5 }], condition: "rec", mode: "data", source: "scouting", evidence: "Exemplo da base de dados ou ficha de registo" },
  { code: "3.2.2.6", criterion: 3, group: "3.2.2", text: "Procedimentos de comunicação com pais, clubes e outros agentes, segundo as linhas de ética da FPF", points: 0.75, mandatory: "Q", condition: "rec", mode: "document", source: "scouting", evidence: "Capítulo + exemplos de pedidos de autorização a clubes de origem. Dossier completo na visita técnica" },
  { code: "3.2.3.1", criterion: 3, group: "3.2.3", text: "Angariação proativa com os procedimentos definidos e documentados", points: 0.5, mandatory: "E", mode: "document", source: "documents", evidence: "Procedimentos + exemplos de materiais de comunicação", note: "Vale 4 pontos nos clubes que não fazem recrutamento." },
  { code: "3.2.3.2", criterion: 3, group: "3.2.3", text: "Base de dados organizada dos praticantes angariados", points: 0.75, mode: "data", source: "teams", evidence: "Exemplo da base de dados ou ficha de registo", note: "Vale 1,25 pontos nos clubes que não fazem recrutamento." },
  { code: "3.3.1", criterion: 3, group: "3.3", text: "Os praticantes não-nacionais recrutados estão legalmente em Portugal", points: 0.25, mandatory: "C", condition: "nn", mode: "document", source: "documents", evidence: "Carta-convite, declaração da AIMA ou similar" },
  { code: "3.3.2", criterion: 3, group: "3.3", text: "O clube assegura a estadia, o acompanhamento e o regresso ao país de origem", points: 0.25, mandatory: "C", condition: "nn", mode: "document", source: "documents", evidence: "Declaração de responsabilidade do clube", note: "O manual escreve 0,5 nesta questão, mas o subcritério vale 0,75 no total. Ficou 0,25 até confirmar." },
  { code: "3.3.3", criterion: 3, group: "3.3", text: "O clube informa a FPF em 48 horas da chegada, da permanência e do regresso", points: 0.25, mandatory: "C", condition: "nn", mode: "document", source: "documents", evidence: "Exemplo do e-mail para estrangeiros@fpf.pt" },
  { code: "3.4.1", criterion: 3, group: "3.4", text: "Há mais praticantes em Petizes, Traquinas e Benjamins do que em Infantis e Iniciados", points: 0.25, mode: "data", source: "teams" },
  { code: "3.4.2", criterion: 3, group: "3.4", text: "Há mais praticantes em Infantis e Iniciados do que em Juvenis", points: 0.25, mode: "data", source: "teams" },
  { code: "3.4.3", criterion: 3, group: "3.4", text: "Há mais praticantes em Juvenis do que em Juniores", points: 0.25, mode: "data", source: "teams" },
  { code: "3.5.1", criterion: 3, group: "3.5", text: "Documentos do critério com qualidade, profundidade e coerência bastante acima da média", points: 1, assessor: true, mode: "assessor", source: "assessor" },
  { code: "3.5.2", criterion: 3, group: "3.5", text: "Preocupação prática e efetiva com as linhas de ética no recrutamento, verificada no terreno", points: 1, assessor: true, mode: "assessor", source: "assessor" },

  // 4 · Formação desportiva (18 pontos)
  { code: "4.1.1", criterion: 4, group: "4.1", text: "Documento Orientador Técnico organizado, com índice e referências", points: 0.5, mandatory: "Q", mode: "document", source: "documents", evidence: "Documento completo" },
  { code: "4.1.2", criterion: 4, group: "4.1", text: "Modelo de competências a desenvolver por posição", points: 0.5, mandatory: "Q", mode: "document", source: "documents", evidence: "Capítulo do documento" },
  { code: "4.1.3", criterion: 4, group: "4.1", text: "Modelo de competências por idade, a partir da fase de especialização", points: 0.5, mode: "document", source: "documents", evidence: "Capítulo do documento" },
  { code: "4.1.4", criterion: 4, group: "4.1", text: "Objetivos no ensino do jogo, respeitando as etapas de desenvolvimento", points: 0.5, mandatory: "E", mode: "document", source: "documents", evidence: "Capítulo do documento" },
  { code: "4.1.5", criterion: 4, group: "4.1", text: "Desenvolvimento das capacidades motoras por etapa e como se operacionaliza na época", points: 0.5, mode: "document", source: "documents", evidence: "Capítulo do documento" },
  { code: "4.1.6", criterion: 4, group: "4.1", text: "Desenvolvimento psicológico por etapa e como se operacionaliza na época", points: 0.5, mode: "document", source: "documents", evidence: "Capítulo do documento" },
  { code: "4.1.7", criterion: 4, group: "4.1", text: "Processos de modelação: número de treinos semanais, duração e ocupação do espaço por escalão", points: 0.5, mode: "document", source: "documents", evidence: "Capítulo do documento, coerente com o mapa de ocupação do espaço" },
  { code: "4.1.8", criterion: 4, group: "4.1", text: "Modelo de jogo para futebol de 7, de 9 e de 11", points: 0.5, mode: "document", source: "training", evidence: "Capítulo do documento" },
  { code: "4.1.9", criterion: 4, group: "4.1", text: "Perfil do treinador por escalão", points: 0.25, mandatory: "Q", mode: "document", source: "documents", evidence: "Capítulo do documento" },
  { code: "4.1.10", criterion: 4, group: "4.1", text: "O documento é conhecido por toda a estrutura técnica", points: 0.25, mandatory: "Q", mode: "data", source: "training-actions", evidence: "Registo de uma formação por época com todas as equipas técnicas" },
  { code: "4.2.1", criterion: 4, group: "4.2", text: "Dossier de treino padronizado, com a mesma estrutura em todas as equipas", points: 0.25, mandatory: "E", mode: "data", source: "training", evidence: "Índice dos dossiers" },
  { code: "4.2.2", criterion: 4, group: "4.2", text: "Dossier de treino supervisionado pelo diretor ou coordenador técnico", points: 0.25, mandatory: "E", mode: "data", source: "training" },
  { code: "4.2.3", criterion: 4, group: "4.2", text: "Dossier de qualquer escalão organizado, atualizado e pronto a mostrar na visita técnica", points: 1, mode: "data", source: "training", evidence: "Dossiers completos de todos os escalões na visita. Pode anexar um link de acesso" },
  { code: "4.2.4", criterion: 4, group: "4.2", text: "Plantel e fichas individuais, com avaliação comportamental e de desempenho", points: 0.5, mandatory: "T", mode: "data", source: "evaluations", evidence: "Exemplo de plantel e de fichas individuais" },
  { code: "4.2.5", criterion: 4, group: "4.2", text: "Objetivos formativos definidos e controlo do seu cumprimento", points: 0.5, mandatory: "Q", mode: "data", source: "training", evidence: "Exemplo de objetivos e da sua avaliação" },
  { code: "4.2.6", criterion: 4, group: "4.2", text: "Planeamento anual ou de mesociclos, microciclo e registo dos conteúdos das unidades de treino", points: 1, mandatory: "T", mode: "data", source: "training", evidence: "Exemplos de planeamento, microciclo e unidade de treino" },
  { code: "4.2.7", criterion: 4, group: "4.2", text: "Pelo menos um treino semanal em campo inteiro para as equipas de Sub-15 a Sub-19", points: 0.5, mandatory: "Q", mode: "data", source: "training", evidence: "Mapa semanal de treinos no mapa-tipo da FPF" },
  { code: "4.2.8", criterion: 4, group: "4.2", text: "Convocatórias e avaliação dos jogos, com reflexão e não só estatística", points: 0.5, mode: "data", source: "matches", evidence: "Exemplos de convocatória e de avaliação de jogo" },
  { code: "4.2.9", criterion: 4, group: "4.2", text: "Materiais e equipamentos usados nos treinos de cada escalão", points: 0.5, mode: "data", source: "training", evidence: "Descrição de materiais e equipamentos" },
  { code: "4.3.1.1", criterion: 4, group: "4.3.1", text: "Plano de transição definido e documentado", points: 0.5, mandatory: "E", mode: "document", source: "documents", evidence: "Plano de transição" },
  { code: "4.3.1.2", criterion: 4, group: "4.3.1", text: "O plano prevê retenção e encaminhamento de quem não continua no clube", points: 0.5, mode: "document", source: "documents", evidence: "Plano de transição" },
  { code: "4.3.1.3", criterion: 4, group: "4.3.1", text: "Transição feita com equipa B, Sub-23 ou clube satélite", points: 0.5, mode: "document", source: "documents" },
  { code: "4.3.1.4", criterion: 4, group: "4.3.1", text: "Transição feita com acordos documentados com outros clubes", points: 0.5, mode: "document", source: "documents", evidence: "Acordos assinados ou histórico de fluxo de jogadores" },
  { code: "4.3.2.1", criterion: 4, group: "4.3.2", text: "Planeamento anual de reuniões entre os escalões de formação", points: 0.5, mode: "data", source: "calendar", evidence: "Planeamento anual das reuniões", note: "Vale 1 ponto nos clubes sem escalão sénior." },
  { code: "4.3.2.2", criterion: 4, group: "4.3.2", text: "Planeamento anual de reuniões entre a formação e a estrutura sénior", points: 0.5, condition: "sen", mode: "data", source: "calendar", evidence: "Planeamento anual das reuniões" },
  { code: "4.3.2.3", criterion: 4, group: "4.3.2", text: "Temas das reuniões de articulação definidos", points: 0.25, mode: "data", source: "calendar", evidence: "Temas por reunião" },
  { code: "4.3.2.4", criterion: 4, group: "4.3.2", text: "Atas ou relatórios das reuniões de articulação", points: 0.25, mode: "data", source: "calendar", evidence: "Exemplo de ata" },
  { code: "4.4.1.1", criterion: 4, group: "4.4", text: "Correspondência total entre o Documento Orientador Técnico e o treino observado", points: 2, assessor: true, mode: "assessor", source: "assessor" },
  { code: "4.4.1.2", criterion: 4, group: "4.4", text: "Correspondência total entre o dossier de treino e o treino observado", points: 2, assessor: true, mode: "assessor", source: "assessor" },
  { code: "4.4.2", criterion: 4, group: "4.4", text: "Documentos do critério com qualidade e coerência bastante acima da média", points: 1, assessor: true, mode: "assessor", source: "assessor" },

  // 5 · Acompanhamento médico-desportivo (13 pontos)
  { code: "5.1.1", criterion: 5, group: "5.1", text: "Plano de atividades do departamento médico, assinado pelo coordenador clínico e pela direção", tiers: [{ label: "Conteúdos I a IV: organograma, orçamento, alocação a treinos e jogos, apoio a D.R.E.", points: 0.25, mandatory: "C" }, { label: "Mais V e VI: atos clínicos e avaliação pré-participação", points: 0.5, mandatory: "T" }, { label: "Mais VII a X: controlo médico do treino, formação, comunicação, métricas", points: 1, mandatory: "Q" }], mode: "document", source: "documents", evidence: "Plano de atividades, incluindo os protocolos com entidades externas" },
  { code: "5.2.1", criterion: 5, group: "5.2", text: "Coordenação clínica identificada, com registo criminal, CV, cédula e declaração de responsabilidade", tiers: [{ label: "Técnico de SBV e DAE", points: 0.25, mandatory: "C" }, { label: "Fisioterapeuta ou enfermeiro", points: 0.5, mandatory: "E" }, { label: "Médico", points: 0.75, mandatory: "T" }, { label: "Médico pós-graduado em medicina desportiva", points: 1, mandatory: "Q" }, { label: "Médico especialista em medicina desportiva", points: 1.25 }], mode: "data", source: "staff", evidence: "Declaração assinada a assumir o departamento e o plano de atividades" },
  { code: "5.2.2", criterion: 5, group: "5.2", text: "Outros médicos a colaborar, com registo criminal, CV e cédula", points: 0.25, mode: "data", source: "staff" },
  { code: "5.2.3", criterion: 5, group: "5.2", text: "Fisioterapeutas ou enfermeiros, com registo criminal, CV e cédula", points: 0.25, mandatory: "T", mode: "data", source: "staff" },
  { code: "5.2.4", criterion: 5, group: "5.2", text: "Nutricionistas, com registo criminal, CV e cédula", points: 0.25, mandatory: "Q", mode: "data", source: "staff" },
  { code: "5.2.5", criterion: 5, group: "5.2", text: "Psicólogos, com registo criminal, CV e cédula", points: 0.25, mode: "data", source: "staff" },
  { code: "5.2.6", criterion: 5, group: "5.2", text: "Fisiologistas do exercício, com registo criminal, CV e cédula", points: 0.25, mode: "data", source: "staff" },
  { code: "5.2.7", criterion: 5, group: "5.2", text: "Técnicos de SBV e DAE, com registo criminal, CV e comprovativo da formação", points: 0.25, mandatory: "C", mode: "data", source: "staff" },
  { code: "5.2.8", criterion: 5, group: "5.2", text: "Como são garantidos os serviços médicos", tiers: [{ label: "Solução mista ou só externa, com acordos formalizados", points: 0.25, mandatory: "T" }, { label: "Solução interna integral", points: 0.5 }], mode: "document", source: "documents" },
  { code: "5.3.1", criterion: 5, group: "5.3", text: "Infogramas de emergência médica afixados nos locais de treino e jogo ou plastificados nas malas", points: 0.25, mandatory: "C", mode: "document", source: "facilities", evidence: "Infogramas + fotografia afixados ou na mala" },
  { code: "5.3.2", criterion: 5, group: "5.3", text: "DAE em todos os recintos, a funcionar e com as pás dentro da validade", points: 0.25, mandatory: "T", mode: "data", source: "facilities", evidence: "Fotografia de cada DAE ligado no recinto + validade das pás" },
  { code: "5.3.3", criterion: 5, group: "5.3", text: "Mala de campo com primeiros socorros, talas e ligaduras", points: 0.25, mandatory: "C", mode: "document", source: "facilities", evidence: "Fotografias do material" },
  { code: "5.3.4", criterion: 5, group: "5.3", text: "Mala de campo também com canadianas, plano duro com imobilizador de cabeça e colar cervical", points: 0.25, mandatory: "Q", mode: "document", source: "facilities", evidence: "Fotografias do material" },
  { code: "5.4.1.1", criterion: 5, group: "5.4.1", text: "Profissional de saúde em todos os treinos e jogos em casa de todas as equipas", tiers: [{ label: "Outros profissionais com SBV e DAE, coordenados por médico, fisioterapeuta ou enfermeiro", points: 0.5, mandatory: "E" }, { label: "Fisioterapeuta ou enfermeiro presente em todos", points: 0.75, mandatory: "Q" }], mode: "data", source: "training", evidence: "Mapa semanal de treinos com a estrutura médica alocada + fichas de jogo do último mês" },
  { code: "5.4.1.2", criterion: 5, group: "5.4.1", text: "Técnico de SBV e DAE em todos os treinos e jogos em casa de todas as equipas", points: 0.25, mandatory: "C", mode: "data", source: "training", evidence: "Mapa semanal de treinos + fichas de jogo do último mês" },
  { code: "5.4.2.1", criterion: 5, group: "5.4.2", text: "Registos clínicos acessíveis ao departamento médico", tiers: [{ label: "Só registo de ocorrências por equipa e praticante", points: 0.25, mandatory: "E" }, { label: "Registos de consultas, ficheiro clínico completo e ocorrências", points: 1, mandatory: "T" }], mode: "data", source: "clinical", evidence: "Exemplos de registos clínicos, ficheiro clínico e ocorrências" },
  { code: "5.4.2.2", criterion: 5, group: "5.4.2", text: "Disponibilidade de consulta médica", tiers: [{ label: "Consulta em instalações externas", points: 0.25 }, { label: "Médico todas as semanas nas instalações", points: 1 }], mode: "data", source: "clinical", evidence: "Registo de presenças do médico ou de consultas, planeado contra realizado" },
  { code: "5.4.2.3", criterion: 5, group: "5.4.2", text: "Serviço de psicologia desportiva e de performance", points: 0.25, mode: "document", source: "documents", evidence: "Metodologia de referenciação e acompanhamento" },
  { code: "5.4.2.4", criterion: 5, group: "5.4.2", text: "Serviço de psicologia na área social e escolar", points: 0.25, mode: "document", source: "documents", evidence: "Metodologia de referenciação e acompanhamento" },
  { code: "5.4.3.1", criterion: 5, group: "5.4.3", text: "Acesso aos exames médico-desportivos dos praticantes", points: 0.75, mode: "data", source: "clinical", evidence: "Exemplos de exames da época. O acesso à generalidade é verificado na visita" },
  { code: "5.4.3.2", criterion: 5, group: "5.4.3", text: "Avaliações de saúde complementares, duas diferentes, em pelo menos dois escalões", points: 0.25, mode: "data", source: "clinical", evidence: "Descrição das avaliações + exemplo" },
  { code: "5.4.3.3", criterion: 5, group: "5.4.3", text: "Avaliações de fisiologia e prevenção de lesões, duas diferentes, em pelo menos dois escalões", points: 0.25, mode: "data", source: "clinical", evidence: "Descrição das avaliações + exemplo" },
  { code: "5.4.3.4", criterion: 5, group: "5.4.3", text: "Avaliações nutricionais e planos alimentares em pelo menos dois escalões", points: 0.25, mode: "data", source: "clinical", evidence: "Exemplos de avaliação e de plano alimentar" },
  { code: "5.4.3.5", criterion: 5, group: "5.4.3", text: "Avaliação nutricional e plano alimentar de todos os praticantes D.R.E.", points: 0.25, mandatory: "C", condition: "dre", mode: "data", source: "clinical", evidence: "Avaliações e planos de todos os D.R.E." },
  { code: "5.4.4.1", criterion: 5, group: "5.4.4", text: "Simulação anual de atuação em emergência médica", points: 0.25, mode: "data", source: "training-actions", evidence: "Descrição da simulação + lista de presenças assinada" },
  { code: "5.4.4.2", criterion: 5, group: "5.4.4", text: "Médicos com formação complementar em saúde e performance nos últimos 5 anos", points: 0.25, mode: "data", source: "staff", evidence: "Comprovativos" },
  { code: "5.4.4.3", criterion: 5, group: "5.4.4", text: "Enfermeiros e fisioterapeutas com formação complementar nos últimos 5 anos", points: 0.25, mode: "data", source: "staff", evidence: "Comprovativos" },
  { code: "5.4.4.4", criterion: 5, group: "5.4.4", text: "Nutricionistas ou psicólogos com formação complementar nos últimos 5 anos", points: 0.25, mode: "data", source: "staff", evidence: "Comprovativos" },
  { code: "5.4.4.5", criterion: 5, group: "5.4.4", text: "Outros colaboradores com formação complementar em saúde nos últimos 5 anos", points: 0.25, mode: "data", source: "staff", evidence: "Comprovativos" },
  { code: "5.4.4.6", criterion: 5, group: "5.4.4", text: "Formações de saúde dadas pelo departamento médico a praticantes e encarregados", points: 0.25, mode: "data", source: "training-actions", evidence: "Comprovativos das formações" },
  { code: "5.5.1", criterion: 5, group: "5.5", text: "Documentos cuidados e correspondência com a operação verificada no terreno", points: 0.5, assessor: true, mode: "assessor", source: "assessor" },
  { code: "5.5.2", criterion: 5, group: "5.5", text: "Material, espaço, privacidade e higiene do departamento médico muito acima da média", points: 0.5, assessor: true, mode: "assessor", source: "assessor" },

  // 6 · Acompanhamento escolar, pessoal e social (9 pontos)
  { code: "6.1.1.1", criterion: 6, group: "6.1", text: "Conhece as escolas dos praticantes e tem identificado o interlocutor de cada uma", points: 0.75, mode: "data", source: "school", evidence: "Lista de escolas com o número de praticantes e o contacto do interlocutor" },
  { code: "6.1.2.1", criterion: 6, group: "6.1", text: "Protocolos ou histórico de relacionamento com as escolas", points: 0.75, mode: "document", source: "documents", evidence: "Protocolos assinados ou histórico de contactos" },
  { code: "6.1.3.1", criterion: 6, group: "6.1", text: "Registo organizado e permanente do aproveitamento escolar de todos os praticantes", points: 0.5, mandatory: "T", mode: "data", source: "school", evidence: "Folha de análise de um escalão completo: 3.º período do ano anterior e 1.º período deste ano" },
  { code: "6.1.3.2", criterion: 6, group: "6.1", text: "Mecanismos de incentivo e de correção do comportamento e aproveitamento escolar, definidos e aplicados", points: 0.5, mandatory: "T", mode: "document", source: "documents", evidence: "Descrição dos mecanismos + exemplos de casos" },
  { code: "6.2.1", criterion: 6, group: "6.2", text: "Responsável pelo acompanhamento escolar e social (Gestor de Carreira Dual), com registo criminal e CV", tiers: [{ label: "Acumula com outras funções", points: 0.25, mandatory: "C" }, { label: "Exclusivo nesta função", points: 0.5 }], mode: "data", source: "staff", evidence: "Descrição das tarefas regulares", note: "Sem praticantes D.R.E. vale 1 e 1,5 pontos." },
  { code: "6.3.1", criterion: 6, group: "6.3", text: "Responsável pelo acompanhamento dos praticantes D.R.E., sempre contactável", tiers: [{ label: "Acumula com outras funções", points: 0.25, mandatory: "C" }, { label: "Exclusivo nesta função", points: 0.5 }], condition: "dre", mode: "data", source: "staff", evidence: "Descrição das tarefas regulares" },
  { code: "6.3.2", criterion: 6, group: "6.3", text: "Acompanhamento dos D.R.E. nas deslocações para a escola e os treinos", points: 0.5, condition: "dre", mode: "document", source: "documents", evidence: "Descrição de como o transporte é assegurado" },
  { code: "6.4.1", criterion: 6, group: "6.4", text: "Diretor, Gestor de Carreira Dual ou Responsável D.R.E. fez o curso do IPDJ de proteção de crianças e jovens", points: 0.25, mandatory: "T", mode: "data", source: "staff", evidence: "Certificado do curso (4 horas)" },
  { code: "6.4.2", criterion: 6, group: "6.4", text: "O coordenador técnico também fez o curso do IPDJ", points: 0.25, mode: "data", source: "staff", evidence: "Certificado do curso" },
  { code: "6.5.1", criterion: 6, group: "6.5", text: "Formações anuais aos praticantes em nutrição, integridade e leis do jogo", points: 0.5, mandatory: "T", mode: "data", source: "training-actions", evidence: "Planeamento anual + presenças, conteúdos e fotografias de três ações" },
  { code: "6.5.2", criterion: 6, group: "6.5", text: "Número de formações anuais aos praticantes, uma delas sobre direitos humanos (Amnistia Internacional)", tiers: [{ label: "5 a 8 ações", points: 0.5, mandatory: "Q" }, { label: "Mais de 8 ações", points: 1 }], mode: "data", source: "training-actions", evidence: "Planeamento anual + presenças, conteúdos e fotografias" },
  { code: "6.5.3", criterion: 6, group: "6.5", text: "Formação anual de ética desportiva para os encarregados de todos os escalões", points: 0.75, mandatory: "E", mode: "data", source: "training-actions", evidence: "Presenças, conteúdos e fotografias. Recomendada até 31 de dezembro" },
  { code: "6.6.1", criterion: 6, group: "6.6", text: "Praticantes com idade de Sub-19 que concluíram ou frequentam o 12.º ano", tiers: [{ label: "50 a 75%", points: 0.25 }, { label: "75 a 90%", points: 0.5 }, { label: "Mais de 90%", points: 0.75 }], mode: "data", source: "school", evidence: "Folha resumo dos Sub-19 com a escolaridade e comprovativos" },
  { code: "6.6.2", criterion: 6, group: "6.6", text: "Há praticantes Sub-19 no ensino superior", points: 0.5, mode: "data", source: "school", evidence: "Comprovativo de frequência" },
  { code: "6.7.1", criterion: 6, group: "6.7", text: "Correspondência entre os documentos e o acompanhamento feito no terreno, verificada com os responsáveis", points: 1, assessor: true, mode: "assessor", source: "assessor" },

  // 7 · Recursos humanos (16 pontos)
  { code: "7.1.1", criterion: 7, group: "7.1", text: "Diretor da entidade formadora identificado, com registo criminal e CV", points: 0.5, mandatory: "T", mode: "data", source: "staff" },
  { code: "7.1.2", criterion: 7, group: "7.1", text: "Descrição de funções e atribuições do diretor", points: 0.5, mode: "document", source: "staff", evidence: "Descrição de funções" },
  { code: "7.1.3", criterion: 7, group: "7.1", text: "O diretor tem nesta função a sua atividade profissional principal", points: 0.5, mode: "data", source: "staff" },
  { code: "7.1.4", criterion: 7, group: "7.1", text: "O diretor não acumula outras funções no clube", points: 0.75, mode: "data", source: "staff" },
  { code: "7.1.5", criterion: 7, group: "7.1", text: "O diretor fez o curso de Diretor de Entidades Formadoras (Portugal Football School)", points: 0.5, mode: "data", source: "staff", evidence: "Diploma" },
  { code: "7.1.6", criterion: 7, group: "7.1", text: "O diretor fez o curso de Formação de Dirigentes ou formação similar", points: 0.5, mode: "data", source: "staff", evidence: "Diploma" },
  { code: "7.1.7", criterion: 7, group: "7.1", text: "O diretor tem formação superior", points: 0.5, mode: "data", source: "staff", evidence: "Certificado de habilitações" },
  { code: "7.2.1.1", criterion: 7, group: "7.2.1", text: "Coordenador técnico identificado, com registo criminal, CV, TPTD e cartão do Score na função", points: 0.5, mandatory: "E", mode: "data", source: "staff" },
  { code: "7.2.1.2", criterion: 7, group: "7.2.1", text: "Descrição de funções e atribuições do coordenador técnico", points: 0.5, mode: "document", source: "staff", evidence: "Descrição de funções" },
  { code: "7.2.1.3", criterion: 7, group: "7.2.1", text: "O coordenador técnico está em funções pelo menos nas duas últimas épocas", points: 0.5, mode: "data", source: "staff" },
  { code: "7.2.1.4", criterion: 7, group: "7.2.1", text: "O coordenador técnico não acumula com diretor nem com treinador", points: 0.75, mode: "data", source: "staff" },
  { code: "7.2.1.5", criterion: 7, group: "7.2.1", text: "O coordenador técnico fez a formação em coordenação técnica (Portugal Football School)", points: 0.5, mode: "data", source: "staff", evidence: "Diploma" },
  { code: "7.2.1.6", criterion: 7, group: "7.2.1", text: "Grau de treinador do coordenador técnico", tiers: [{ label: "Grau I", points: 0.25, mandatory: "E" }, { label: "Grau II ou estagiário de Grau II", points: 0.5, mandatory: "T" }, { label: "Grau III", points: 0.75 }, { label: "Grau IV", points: 1 }], mode: "data", source: "staff" },
  { code: "7.2.1.7", criterion: 7, group: "7.2.1", text: "Experiência do coordenador técnico como treinador", tiers: [{ label: "Até 3 anos", points: 0.25 }, { label: "4 a 5 anos", points: 0.5 }, { label: "6 ou mais anos", points: 1 }], mode: "data", source: "staff" },
  { code: "7.2.2.1", criterion: 7, group: "7.2.2", text: "Todos os treinadores identificados, com registo criminal e CV", points: 0.5, mandatory: "C", mode: "data", source: "staff" },
  { code: "7.2.2.2", criterion: 7, group: "7.2.2", text: "TPTD de todos os treinadores submetido e válido", points: 0.5, mandatory: "C", mode: "data", source: "staff" },
  { code: "7.2.2.3", criterion: 7, group: "7.2.2", text: "Pelo menos 20% dos treinadores com este grau", tiers: [{ label: "Grau I", points: 0.25 }, { label: "Grau II", points: 0.5 }, { label: "Grau III", points: 0.75 }, { label: "Grau IV", points: 1 }], mode: "data", source: "staff" },
  { code: "7.2.2.4", criterion: 7, group: "7.2.2", text: "Rácio de treinadores por equipa", tiers: [{ label: "1 treinador para 2 equipas", points: 0.25, mandatory: "Q" }, { label: "1 treinador por equipa", points: 0.5 }, { label: "2 treinadores por equipa", points: 0.75 }, { label: "Mais de 2 por equipa", points: 1 }], mode: "data", source: "staff" },
  { code: "7.3.1", criterion: 7, group: "7.3", text: "Analistas de desempenho, com registo criminal e CV", points: 0.5, mode: "data", source: "staff", evidence: "Descrição do trabalho + exemplo de relatório" },
  { code: "7.3.2", criterion: 7, group: "7.3", text: "Estagiários de treino desportivo, com registo criminal, CV e declaração de estágio", points: 0.5, mode: "data", source: "staff" },
  { code: "7.3.3", criterion: 7, group: "7.3", text: "Estagiários de gestão desportiva, com registo criminal, CV e declaração de estágio", points: 0.5, mode: "data", source: "staff" },
  { code: "7.4.1", criterion: 7, group: "7.4", text: "Secretário técnico ou team manager, com registo criminal e CV", points: 0.25, mode: "data", source: "staff" },
  { code: "7.4.2", criterion: 7, group: "7.4", text: "O team manager fez o curso de Team Manager ou formação similar", points: 0.25, mode: "data", source: "staff", evidence: "Diploma" },
  { code: "7.4.3", criterion: 7, group: "7.4", text: "Outros administrativos, com registo criminal e CV", points: 0.5, mode: "data", source: "staff" },
  { code: "7.4.4", criterion: 7, group: "7.4", text: "Técnicos de equipamentos, com registo criminal e CV", points: 0.5, mode: "data", source: "staff" },
  { code: "7.4.5", criterion: 7, group: "7.4", text: "Motoristas identificados, internos ou por protocolo", points: 0.25, mode: "data", source: "staff" },
  { code: "7.4.6", criterion: 7, group: "7.4", text: "Pelo menos um motorista com habilitação para transporte coletivo de crianças", points: 0.25, mode: "data", source: "staff", evidence: "Habilitação" },
  { code: "7.5.1", criterion: 7, group: "7.5", text: "Diretor e coordenador técnico em funções toda a época, pessoas diferentes e empenhadas no processo", points: 1, assessor: true, mode: "assessor", source: "assessor" },

  // 8 · Instalações e logística (10 pontos)
  { code: "8.1.1", criterion: 8, group: "8.1", text: "Iluminação adequada para os treinos", points: 0.25, mandatory: "C", mode: "document", source: "facilities", evidence: "Fotografias de todos os campos com a iluminação acesa" },
  { code: "8.1.2", criterion: 8, group: "8.1", text: "Piso dos campos de treino", tiers: [{ label: "Pelados ou relvados", points: 0.25 }, { label: "Pelados e relvados, com preferência pelos relvados", points: 0.25, mandatory: "E" }, { label: "Só relvados, naturais ou sintéticos", points: 0.25, mandatory: "T" }, { label: "Só relvados em boas condições de conservação", points: 0.75 }], mode: "data", source: "facilities", evidence: "Fotografias de todos os campos" },
  { code: "8.2.1", criterion: 8, group: "8.2", text: "Vestiários e balneários com capacidade adequada", tiers: [{ label: "Só vestiários", points: 0.25, mandatory: "C" }, { label: "Vestiários e balneários", points: 0.5, mandatory: "E" }, { label: "Com água quente, WC, ventilação, bancos, cabides e zona seca separada", points: 1, mandatory: "T" }], mode: "document", source: "facilities", evidence: "Fotografias em todos os campos" },
  { code: "8.3.1", criterion: 8, group: "8.3", text: "Gabinete para o diretor e o coordenador técnico", points: 0.5, mode: "document", source: "facilities", evidence: "Fotografia" },
  { code: "8.3.2", criterion: 8, group: "8.3", text: "O gabinete tem internet, impressão, postos informatizados e espaço de reunião", points: 0.25, mode: "document", source: "facilities", evidence: "Fotografia" },
  { code: "8.3.3", criterion: 8, group: "8.3", text: "Sala de trabalho dos treinadores, com secretárias e mesa de reunião", points: 0.5, mandatory: "E", mode: "document", source: "facilities", evidence: "Fotografia" },
  { code: "8.3.4", criterion: 8, group: "8.3", text: "A sala dos treinadores tem internet, impressão e postos informatizados", points: 0.25, mode: "document", source: "facilities", evidence: "Fotografia" },
  { code: "8.4.1", criterion: 8, group: "8.4", text: "Sala de reunião para staff e para receber pais", points: 0.5, mode: "document", source: "facilities", evidence: "Fotografia" },
  { code: "8.4.2", criterion: 8, group: "8.4", text: "Sala de estudo e formação, com mesas, cadeiras e quadro", points: 0.5, mode: "document", source: "facilities", evidence: "Fotografia" },
  { code: "8.4.3", criterion: 8, group: "8.4", text: "As salas têm computadores, internet, impressão e projeção", points: 0.25, mode: "document", source: "facilities", evidence: "Fotografia" },
  { code: "8.5.1", criterion: 8, group: "8.5", text: "Espaço de trabalho para os serviços administrativos", points: 0.25, mandatory: "C", mode: "document", source: "facilities", evidence: "Fotografia" },
  { code: "8.5.2", criterion: 8, group: "8.5", text: "O espaço administrativo tem computadores, comunicações, internet e impressão", points: 0.25, mode: "document", source: "facilities", evidence: "Fotografia" },
  { code: "8.6.1", criterion: 8, group: "8.6", text: "Ginásio", tiers: [{ label: "Só acordo com ginásio externo", points: 0.25 }, { label: "Ginásio nas instalações", points: 0.5 }], mode: "document", source: "facilities", evidence: "Fotografia ou acordo assinado" },
  { code: "8.6.2", criterion: 8, group: "8.6", text: "Ginásio com capacidade para 10 praticantes em simultâneo e equipamento adequado", points: 0.25, mode: "document", source: "facilities", evidence: "Fotografia" },
  { code: "8.7.1", criterion: 8, group: "8.7", text: "Alojamento D.R.E. com quartos de dimensão e ocupação adequadas", points: 0.25, mandatory: "C", condition: "dre", mode: "document", source: "facilities", evidence: "Fotografias" },
  { code: "8.7.2", criterion: 8, group: "8.7", text: "Alojamento D.R.E. com casas de banho", points: 0.25, mandatory: "C", condition: "dre", mode: "document", source: "facilities", evidence: "Fotografias" },
  { code: "8.7.3", criterion: 8, group: "8.7", text: "Alojamento D.R.E. com sala de refeições", points: 0.25, mandatory: "C", condition: "dre", mode: "document", source: "facilities", evidence: "Fotografias" },
  { code: "8.7.4", criterion: 8, group: "8.7", text: "Alojamento D.R.E. com espaço de convívio", points: 0.25, mandatory: "C", condition: "dre", mode: "document", source: "facilities", evidence: "Fotografias" },
  { code: "8.7.5", criterion: 8, group: "8.7", text: "Alojamento D.R.E. com espaço de estudo", points: 0.25, mandatory: "C", condition: "dre", mode: "document", source: "facilities", evidence: "Fotografias" },
  { code: "8.7.6", criterion: 8, group: "8.7", text: "Alojamento D.R.E. com serviço de lavandaria", points: 0.25, condition: "dre", mode: "document", source: "facilities" },
  { code: "8.7.7", criterion: 8, group: "8.7", text: "Instalações D.R.E. com boas condições de higiene, limpeza e segurança", points: 0.25, mandatory: "C", condition: "dre", mode: "document", source: "facilities", evidence: "Fotografias" },
  { code: "8.8.1", criterion: 8, group: "8.8", text: "Transporte assegurado para os jogos, pelo menos a partir dos Sub-14", points: 0.25, mode: "document", source: "documents", evidence: "Descrição das soluções de transporte" },
  { code: "8.9.1", criterion: 8, group: "8.9", text: "Qualidade global das infraestruturas", tiers: [{ label: "Muito bom, ao nível das melhores da região", points: 0.25 }, { label: "Excelente, ao nível das melhores do país", points: 0.75 }], assessor: true, mode: "assessor", source: "assessor" },
  { code: "8.9.2", criterion: 8, group: "8.9", text: "Localização, concentração da atividade e facilidade de acesso", tiers: [{ label: "Muito bom, até dois complexos", points: 0.25 }, { label: "Excelente, um só complexo", points: 0.75 }], assessor: true, mode: "assessor", source: "assessor" },
  { code: "8.9.3", criterion: 8, group: "8.9", text: "As infraestruturas são mesmo usadas pela formação, e de forma adequada", points: 0.5, assessor: true, mode: "assessor", source: "assessor" },

  // 9 · Produtividade (8 pontos)
  { code: "9.1.1", criterion: 9, group: "9.1", text: "Praticantes com 3 ou mais épocas na formação convocados para a equipa principal nas últimas 6 épocas", tiers: [{ label: "1 praticante", points: 0.5 }, { label: "2 praticantes", points: 1 }, { label: "3 ou mais", points: 2 }], mode: "data", source: "pathway", evidence: "Nomes completos" },
  { code: "9.2.1", criterion: 9, group: "9.2", text: "Praticantes da formação que geraram proveitos de direitos económicos nas últimas 6 épocas", tiers: [{ label: "1 a 5", points: 0.25 }, { label: "6 a 10", points: 0.5 }, { label: "Mais de 10", points: 1 }], mode: "data", source: "finance", evidence: "Lista de direitos gerados e praticantes" },
  { code: "9.3.1", criterion: 9, group: "9.3", text: "Praticantes em convocatórias das seleções nacionais nas últimas 6 épocas", points: 0.5, mode: "data", source: "pathway", evidence: "Nomes + exemplo de convocatória" },
  { code: "9.3.2", criterion: 9, group: "9.3", text: "Praticantes em fichas de jogo das seleções nacionais nas últimas 6 épocas", points: 0.75, mode: "data", source: "pathway", evidence: "Nomes + exemplo de ficha de jogo" },
  { code: "9.3.3", criterion: 9, group: "9.3", text: "Praticantes em convocatórias das seleções distritais nas últimas 6 épocas", points: 0.25, mode: "data", source: "pathway", evidence: "Nomes + exemplo de convocatória" },
  { code: "9.4.1", criterion: 9, group: "9.4", text: "Praticantes da formação em equipas da 1.ª ou 2.ª Liga de outros clubes nas últimas 6 épocas", tiers: [{ label: "1 praticante", points: 0.25 }, { label: "2 praticantes", points: 0.5 }, { label: "3 praticantes", points: 1 }, { label: "4 ou mais", points: 2 }], mode: "data", source: "pathway", evidence: "Nomes completos" },
  { code: "9.5.1", criterion: 9, group: "9.5", text: "Praticantes da formação em equipas de outros clubes em provas nacionais nas últimas 6 épocas", tiers: [{ label: "1 a 3", points: 0.25 }, { label: "4 ou mais", points: 0.5 }], mode: "data", source: "pathway", evidence: "Nomes completos" },
  { code: "9.6.1", criterion: 9, group: "9.6", text: "Juniores de 2.º ano da época passada que continuam a jogar como seniores", tiers: [{ label: "50 a 75%", points: 0.5 }, { label: "75 a 90%", points: 0.75 }, { label: "Mais de 90%", points: 1 }], mode: "data", source: "pathway" },
  ],
};
