/**
 * Um sítio só para ícones.
 *
 * Reexportamos com nomes do nosso domínio ("Whistle" para treinadores) em vez de
 * espalhar nomes da biblioteca pelo código. Trocar de biblioteca — ou desenhar os
 * nossos — passa a ser editar este ficheiro.
 *
 * Traço: 1.5px em toda a app (ver <Icon>), para casar com as hairlines de 1px.
 */
export {
  SquarePen as Pencil,
  LayoutGrid,
  Users,
  Home,
  Shield,
  UserRound as Whistle,
  CalendarDays,
  ClipboardCheck,
  Receipt,
  Megaphone,
  Gauge,
  FileText,
  Settings,
  Search,
  /* Scouting: o binóculo é a área, o olho é a observação. */
  Binoculars,
  Eye,
  /* Sócios: o cartão é o que o clube emite e o sócio guarda. */
  IdCard,
  Clapperboard as Film,
  Bell,
  Plus,
  Check,
  Copy,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronsUpDown,
  ArrowRight,
  ArrowUpRight,
  TrendingUp,
  TrendingDown,
  MoreHorizontal,
  Clock,
  MapPin,
  Mail,
  Phone,
  CreditCard,
  Wallet,
  Download,
  Upload,
  FileSpreadsheet,
  SlidersHorizontal,
  LogOut,
  PanelLeft,
  Send,
  CircleCheck,
  TriangleAlert,
  Sparkle,
  Ban,
  Trash2,
  Link2,
  RefreshCw,
  ExternalLink,
  Loader2,
  Trophy,
  /* Ficha de jogo: o menos fecha o par com o Plus nos contadores. */
  Minus,
  HeartPulse,
  ArrowLeft,
  Ruler,
  Weight,
  Footprints,
  Cake,
  Timer,
  Star,
  Camera,
  Lock,
  Stethoscope,
  Apple,
  Brain,
  Activity,
  /* Área técnica: o haltere é o treino, as formas são a biblioteca de
     exercícios, a rede é o modelo de jogo, a baliza são as bolas paradas. */
  Dumbbell,
  Shapes,
  Network,
  Goal,
  Play,
  Pause,
  /* Editor tático: a mão arrasta a vista, as setas circulares rodam o objeto. */
  Hand,
  RotateCw,
  RotateCcw,
  /* O manípulo de arrasto de uma lista: três linhas, a convenção de sempre. */
  Menu as DragHandle,
  type LucideIcon,
} from "lucide-react";
