/**
 * Um sítio só para ícones.
 *
 * Reexportamos com nomes do nosso domínio ("Whistle" para treinadores) em vez de
 * espalhar nomes da biblioteca pelo código. Trocar de biblioteca — ou desenhar os
 * nossos — passa a ser editar este ficheiro.
 *
 * Traço: 1.5px em toda a app (ver <Icon>), para casar com as hairlines de 1px.
 */
export {
  SquarePen as Pencil,
  LayoutGrid,
  Users,
  Home,
  Shield,
  UserRound as Whistle,
  CalendarDays,
  ClipboardCheck,
  Receipt,
  Megaphone,
  Gauge,
  FileText,
  Settings,
  Search,
  /* Scouting: o binóculo é a área, o olho é a observação. */
  Binoculars,
  Eye,
  /* Sócios: o cartão é o que o clube emite e o sócio guarda. */
  IdCard,
  Clapperboard as Film,
  Bell,
  Plus,
  Check,
  Copy,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronsUpDown,
  ArrowRight,
  ArrowUpRight,
  TrendingUp,
  TrendingDown,
  MoreHorizontal,
  Clock,
  MapPin,
  Mail,
  Phone,
  CreditCard,
  Wallet,
  Download,
  Upload,
  FileSpreadsheet,
  SlidersHorizontal,
  LogOut,
  PanelLeft,
  Send,
  CircleCheck,
  TriangleAlert,
  Sparkle,
  Ban,
  Trash2,
  Link2,
  RefreshCw,
  ExternalLink,
  Loader2,
  Trophy,
  HeartPulse,
  ArrowLeft,
  Ruler,
  Weight,
  Footprints,
  Cake,
  Timer,
  Star,
  Camera,
  Lock,
  Stethoscope,
  Apple,
  Brain,
  Activity,
  type LucideIcon,
} from "lucide-react";
